/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public final class BodyType {
  public final static BodyType staticBody = new BodyType("staticBody", liquidfunJNI.staticBody_get());
  public final static BodyType kinematicBody = new BodyType("kinematicBody");
  public final static BodyType dynamicBody = new BodyType("dynamicBody");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static BodyType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + BodyType.class + " with value " + swigValue);
  }

  private BodyType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private BodyType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private BodyType(String swigName, BodyType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static BodyType[] swigValues = { staticBody, kinematicBody, dynamicBody };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

