/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class ClipVertex {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ClipVertex(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ClipVertex obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ClipVertex obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_ClipVertex(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setV(Vec2 value) {
    liquidfunJNI.ClipVertex_v_set(swigCPtr, this, Vec2.getCPtr(value), value);
  }

  public Vec2 getV() {
    return new Vec2(liquidfunJNI.ClipVertex_v_get(swigCPtr, this), false);
  }

  public void setId(ContactID value) {
    liquidfunJNI.ClipVertex_id_set(swigCPtr, this, ContactID.getCPtr(value), value);
  }

  public ContactID getId() {
    return new ContactID(liquidfunJNI.ClipVertex_id_get(swigCPtr, this), false);
  }

  public ClipVertex() {
    this(liquidfunJNI.new_ClipVertex(), true);
  }

}
