/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class ContactID {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ContactID(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ContactID obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ContactID obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_ContactID(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCf(ContactFeature value) {
    liquidfunJNI.ContactID_cf_set(swigCPtr, this, ContactFeature.getCPtr(value), value);
  }

  public ContactFeature getCf() {
    return new ContactFeature(liquidfunJNI.ContactID_cf_get(swigCPtr, this), false);
  }

  public void setKey(long value) {
    liquidfunJNI.ContactID_key_set(swigCPtr, this, value);
  }

  public long getKey() {
    return liquidfunJNI.ContactID_key_get(swigCPtr, this);
  }

  public ContactID() {
    this(liquidfunJNI.new_ContactID(), true);
  }

}
