/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class ContactEdge {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ContactEdge(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ContactEdge obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ContactEdge obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_ContactEdge(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setOther(Body value) {
    liquidfunJNI.ContactEdge_other_set(swigCPtr, this, Body.getCPtr(value), value);
  }

  public Body getOther() {
    long cPtr = liquidfunJNI.ContactEdge_other_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Body(cPtr, false);
  }

  public void setContact(Contact value) {
    liquidfunJNI.ContactEdge_contact_set(swigCPtr, this, Contact.getCPtr(value), value);
  }

  public Contact getContact() {
    long cPtr = liquidfunJNI.ContactEdge_contact_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Contact(cPtr, false);
  }

  public void setPrev(ContactEdge value) {
    liquidfunJNI.ContactEdge_prev_set(swigCPtr, this, ContactEdge.getCPtr(value), value);
  }

  public ContactEdge getPrev() {
    long cPtr = liquidfunJNI.ContactEdge_prev_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ContactEdge(cPtr, false);
  }

  public void setNext(ContactEdge value) {
    liquidfunJNI.ContactEdge_next_set(swigCPtr, this, ContactEdge.getCPtr(value), value);
  }

  public ContactEdge getNext() {
    long cPtr = liquidfunJNI.ContactEdge_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ContactEdge(cPtr, false);
  }

  public ContactEdge() {
    this(liquidfunJNI.new_ContactEdge(), true);
  }

}
