/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class DistanceInput {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DistanceInput(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DistanceInput obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(DistanceInput obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_DistanceInput(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setProxyA(DistanceProxy value) {
    liquidfunJNI.DistanceInput_proxyA_set(swigCPtr, this, DistanceProxy.getCPtr(value), value);
  }

  public DistanceProxy getProxyA() {
    return new DistanceProxy(liquidfunJNI.DistanceInput_proxyA_get(swigCPtr, this), false);
  }

  public void setProxyB(DistanceProxy value) {
    liquidfunJNI.DistanceInput_proxyB_set(swigCPtr, this, DistanceProxy.getCPtr(value), value);
  }

  public DistanceProxy getProxyB() {
    return new DistanceProxy(liquidfunJNI.DistanceInput_proxyB_get(swigCPtr, this), false);
  }

  public void setTransformA(Transform value) {
    liquidfunJNI.DistanceInput_transformA_set(swigCPtr, this, Transform.getCPtr(value), value);
  }

  public Transform getTransformA() {
    return new Transform(liquidfunJNI.DistanceInput_transformA_get(swigCPtr, this), false);
  }

  public void setTransformB(Transform value) {
    liquidfunJNI.DistanceInput_transformB_set(swigCPtr, this, Transform.getCPtr(value), value);
  }

  public Transform getTransformB() {
    return new Transform(liquidfunJNI.DistanceInput_transformB_get(swigCPtr, this), false);
  }

  public void setUseRadii(boolean value) {
    liquidfunJNI.DistanceInput_useRadii_set(swigCPtr, this, value);
  }

  public boolean getUseRadii() {
    return liquidfunJNI.DistanceInput_useRadii_get(swigCPtr, this);
  }

  public DistanceInput() {
    this(liquidfunJNI.new_DistanceInput(), true);
  }

}
