/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class DistanceOutput {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DistanceOutput(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DistanceOutput obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(DistanceOutput obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_DistanceOutput(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPointA(Vec2 value) {
    liquidfunJNI.DistanceOutput_pointA_set(swigCPtr, this, Vec2.getCPtr(value), value);
  }

  public Vec2 getPointA() {
    return new Vec2(liquidfunJNI.DistanceOutput_pointA_get(swigCPtr, this), false);
  }

  public void setPointB(Vec2 value) {
    liquidfunJNI.DistanceOutput_pointB_set(swigCPtr, this, Vec2.getCPtr(value), value);
  }

  public Vec2 getPointB() {
    return new Vec2(liquidfunJNI.DistanceOutput_pointB_get(swigCPtr, this), false);
  }

  public void setDistance(float value) {
    liquidfunJNI.DistanceOutput_distance_set(swigCPtr, this, value);
  }

  public float getDistance() {
    return liquidfunJNI.DistanceOutput_distance_get(swigCPtr, this);
  }

  public void setIterations(int value) {
    liquidfunJNI.DistanceOutput_iterations_set(swigCPtr, this, value);
  }

  public int getIterations() {
    return liquidfunJNI.DistanceOutput_iterations_get(swigCPtr, this);
  }

  public DistanceOutput() {
    this(liquidfunJNI.new_DistanceOutput(), true);
  }

}
