/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class Filter {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Filter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Filter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Filter obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_Filter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Filter() {
    this(liquidfunJNI.new_Filter(), true);
  }

  public void setCategoryBits(int value) {
    liquidfunJNI.Filter_categoryBits_set(swigCPtr, this, value);
  }

  public int getCategoryBits() {
    return liquidfunJNI.Filter_categoryBits_get(swigCPtr, this);
  }

  public void setMaskBits(int value) {
    liquidfunJNI.Filter_maskBits_set(swigCPtr, this, value);
  }

  public int getMaskBits() {
    return liquidfunJNI.Filter_maskBits_get(swigCPtr, this);
  }

  public void setGroupIndex(short value) {
    liquidfunJNI.Filter_groupIndex_set(swigCPtr, this, value);
  }

  public short getGroupIndex() {
    return liquidfunJNI.Filter_groupIndex_get(swigCPtr, this);
  }

}
