/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class FixtureProxy {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FixtureProxy(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FixtureProxy obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FixtureProxy obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_FixtureProxy(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAabb(AABB value) {
    liquidfunJNI.FixtureProxy_aabb_set(swigCPtr, this, AABB.getCPtr(value), value);
  }

  public AABB getAabb() {
    return new AABB(liquidfunJNI.FixtureProxy_aabb_get(swigCPtr, this), false);
  }

  public void setFixture(Fixture value) {
    liquidfunJNI.FixtureProxy_fixture_set(swigCPtr, this, Fixture.getCPtr(value), value);
  }

  public Fixture getFixture() {
    long cPtr = liquidfunJNI.FixtureProxy_fixture_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Fixture(cPtr, false);
  }

  public void setChildIndex(int value) {
    liquidfunJNI.FixtureProxy_childIndex_set(swigCPtr, this, value);
  }

  public int getChildIndex() {
    return liquidfunJNI.FixtureProxy_childIndex_get(swigCPtr, this);
  }

  public void setProxyId(int value) {
    liquidfunJNI.FixtureProxy_proxyId_set(swigCPtr, this, value);
  }

  public int getProxyId() {
    return liquidfunJNI.FixtureProxy_proxyId_get(swigCPtr, this);
  }

  public FixtureProxy() {
    this(liquidfunJNI.new_FixtureProxy(), true);
  }

}
