/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class FixtureDef {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FixtureDef(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FixtureDef obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FixtureDef obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_FixtureDef(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FixtureDef() {
    this(liquidfunJNI.new_FixtureDef(), true);
  }

  public void setShape(Shape value) {
    liquidfunJNI.FixtureDef_shape_set(swigCPtr, this, Shape.getCPtr(value), value);
  }

  public Shape getShape() {
    long cPtr = liquidfunJNI.FixtureDef_shape_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Shape(cPtr, false);
  }

  public void setUserData(java.lang.Object value) {
    liquidfunJNI.FixtureDef_userData_set(swigCPtr, this, value);
  }

  public java.lang.Object getUserData() {
    return liquidfunJNI.FixtureDef_userData_get(swigCPtr, this);
  }

  public void setFriction(float value) {
    liquidfunJNI.FixtureDef_friction_set(swigCPtr, this, value);
  }

  public float getFriction() {
    return liquidfunJNI.FixtureDef_friction_get(swigCPtr, this);
  }

  public void setRestitution(float value) {
    liquidfunJNI.FixtureDef_restitution_set(swigCPtr, this, value);
  }

  public float getRestitution() {
    return liquidfunJNI.FixtureDef_restitution_get(swigCPtr, this);
  }

  public void setDensity(float value) {
    liquidfunJNI.FixtureDef_density_set(swigCPtr, this, value);
  }

  public float getDensity() {
    return liquidfunJNI.FixtureDef_density_get(swigCPtr, this);
  }

  public void setIsSensor(boolean value) {
    liquidfunJNI.FixtureDef_isSensor_set(swigCPtr, this, value);
  }

  public boolean getIsSensor() {
    return liquidfunJNI.FixtureDef_isSensor_get(swigCPtr, this);
  }

  public void setFilter(Filter value) {
    liquidfunJNI.FixtureDef_filter_set(swigCPtr, this, Filter.getCPtr(value), value);
  }

  public Filter getFilter() {
    return new Filter(liquidfunJNI.FixtureDef_filter_get(swigCPtr, this), false);
  }

}
