/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class FrictionJointDef extends JointDef {
  private transient long swigCPtr;

  protected FrictionJointDef(long cPtr, boolean cMemoryOwn) {
    super(liquidfunJNI.FrictionJointDef_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FrictionJointDef obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FrictionJointDef obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_FrictionJointDef(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public FrictionJointDef() {
    this(liquidfunJNI.new_FrictionJointDef(), true);
  }

  public void initialize(Body bodyA, Body bodyB, Vec2 anchor) {
    liquidfunJNI.FrictionJointDef_initialize(swigCPtr, this, Body.getCPtr(bodyA), bodyA, Body.getCPtr(bodyB), bodyB, Vec2.getCPtr(anchor), anchor);
  }

  public void setLocalAnchorA(Vec2 value) {
    liquidfunJNI.FrictionJointDef_localAnchorA_set(swigCPtr, this, Vec2.getCPtr(value), value);
  }

  public Vec2 getLocalAnchorA() {
    return new Vec2(liquidfunJNI.FrictionJointDef_localAnchorA_get(swigCPtr, this), false);
  }

  public void setLocalAnchorB(Vec2 value) {
    liquidfunJNI.FrictionJointDef_localAnchorB_set(swigCPtr, this, Vec2.getCPtr(value), value);
  }

  public Vec2 getLocalAnchorB() {
    return new Vec2(liquidfunJNI.FrictionJointDef_localAnchorB_get(swigCPtr, this), false);
  }

  public void setMaxForce(float value) {
    liquidfunJNI.FrictionJointDef_maxForce_set(swigCPtr, this, value);
  }

  public float getMaxForce() {
    return liquidfunJNI.FrictionJointDef_maxForce_get(swigCPtr, this);
  }

  public void setMaxTorque(float value) {
    liquidfunJNI.FrictionJointDef_maxTorque_set(swigCPtr, this, value);
  }

  public float getMaxTorque() {
    return liquidfunJNI.FrictionJointDef_maxTorque_get(swigCPtr, this);
  }

}
