/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class FrictionJoint {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FrictionJoint(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FrictionJoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FrictionJoint obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_FrictionJoint(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Vec2 getAnchorA() {
    return new Vec2(liquidfunJNI.FrictionJoint_getAnchorA(swigCPtr, this), true);
  }

  public Vec2 getAnchorB() {
    return new Vec2(liquidfunJNI.FrictionJoint_getAnchorB(swigCPtr, this), true);
  }

  public Vec2 getReactionForce(float inv_dt) {
    return new Vec2(liquidfunJNI.FrictionJoint_getReactionForce(swigCPtr, this, inv_dt), true);
  }

  public float getReactionTorque(float inv_dt) {
    return liquidfunJNI.FrictionJoint_getReactionTorque(swigCPtr, this, inv_dt);
  }

  public Vec2 getLocalAnchorA() {
    return new Vec2(liquidfunJNI.FrictionJoint_getLocalAnchorA(swigCPtr, this), false);
  }

  public Vec2 getLocalAnchorB() {
    return new Vec2(liquidfunJNI.FrictionJoint_getLocalAnchorB(swigCPtr, this), false);
  }

  public void setMaxForce(float force) {
    liquidfunJNI.FrictionJoint_setMaxForce(swigCPtr, this, force);
  }

  public float getMaxForce() {
    return liquidfunJNI.FrictionJoint_getMaxForce(swigCPtr, this);
  }

  public void setMaxTorque(float torque) {
    liquidfunJNI.FrictionJoint_setMaxTorque(swigCPtr, this, torque);
  }

  public float getMaxTorque() {
    return liquidfunJNI.FrictionJoint_getMaxTorque(swigCPtr, this);
  }

  public void dump() {
    liquidfunJNI.FrictionJoint_dump(swigCPtr, this);
  }

}
