/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class GearJointDef extends JointDef {
  private transient long swigCPtr;

  protected GearJointDef(long cPtr, boolean cMemoryOwn) {
    super(liquidfunJNI.GearJointDef_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GearJointDef obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(GearJointDef obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_GearJointDef(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public GearJointDef() {
    this(liquidfunJNI.new_GearJointDef(), true);
  }

  public void setJoint1(Joint value) {
    liquidfunJNI.GearJointDef_joint1_set(swigCPtr, this, Joint.getCPtr(value), value);
  }

  public Joint getJoint1() {
    long cPtr = liquidfunJNI.GearJointDef_joint1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Joint(cPtr, false);
  }

  public void setJoint2(Joint value) {
    liquidfunJNI.GearJointDef_joint2_set(swigCPtr, this, Joint.getCPtr(value), value);
  }

  public Joint getJoint2() {
    long cPtr = liquidfunJNI.GearJointDef_joint2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Joint(cPtr, false);
  }

  public void setRatio(float value) {
    liquidfunJNI.GearJointDef_ratio_set(swigCPtr, this, value);
  }

  public float getRatio() {
    return liquidfunJNI.GearJointDef_ratio_get(swigCPtr, this);
  }

}
