/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class Jacobian {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Jacobian(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Jacobian obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Jacobian obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_Jacobian(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLinear(Vec2 value) {
    liquidfunJNI.Jacobian_linear_set(swigCPtr, this, Vec2.getCPtr(value), value);
  }

  public Vec2 getLinear() {
    return new Vec2(liquidfunJNI.Jacobian_linear_get(swigCPtr, this), false);
  }

  public void setAngularA(float value) {
    liquidfunJNI.Jacobian_angularA_set(swigCPtr, this, value);
  }

  public float getAngularA() {
    return liquidfunJNI.Jacobian_angularA_get(swigCPtr, this);
  }

  public void setAngularB(float value) {
    liquidfunJNI.Jacobian_angularB_set(swigCPtr, this, value);
  }

  public float getAngularB() {
    return liquidfunJNI.Jacobian_angularB_get(swigCPtr, this);
  }

  public Jacobian() {
    this(liquidfunJNI.new_Jacobian(), true);
  }

}
