/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class JointDef {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected JointDef(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JointDef obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(JointDef obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_JointDef(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public JointDef() {
    this(liquidfunJNI.new_JointDef(), true);
  }

  public void setType(int value) {
    liquidfunJNI.JointDef_type_set(swigCPtr, this, value);
  }

  public int getType() {
    return liquidfunJNI.JointDef_type_get(swigCPtr, this);
  }

  public void setUserData(java.lang.Object value) {
    liquidfunJNI.JointDef_userData_set(swigCPtr, this, value);
  }

  public java.lang.Object getUserData() {
    return liquidfunJNI.JointDef_userData_get(swigCPtr, this);
  }

  public void setBodyA(Body value) {
    liquidfunJNI.JointDef_bodyA_set(swigCPtr, this, Body.getCPtr(value), value);
  }

  public Body getBodyA() {
    long cPtr = liquidfunJNI.JointDef_bodyA_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Body(cPtr, false);
  }

  public void setBodyB(Body value) {
    liquidfunJNI.JointDef_bodyB_set(swigCPtr, this, Body.getCPtr(value), value);
  }

  public Body getBodyB() {
    long cPtr = liquidfunJNI.JointDef_bodyB_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Body(cPtr, false);
  }

  public void setCollideConnected(boolean value) {
    liquidfunJNI.JointDef_collideConnected_set(swigCPtr, this, value);
  }

  public boolean getCollideConnected() {
    return liquidfunJNI.JointDef_collideConnected_get(swigCPtr, this);
  }

}
