/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class Joint {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Joint(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Joint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Joint obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  public int getType() {
    return liquidfunJNI.Joint_getType(swigCPtr, this);
  }

  public Body getBodyA() {
    long cPtr = liquidfunJNI.Joint_getBodyA(swigCPtr, this);
    return (cPtr == 0) ? null : new Body(cPtr, false);
  }

  public Body getBodyB() {
    long cPtr = liquidfunJNI.Joint_getBodyB(swigCPtr, this);
    return (cPtr == 0) ? null : new Body(cPtr, false);
  }

  public Vec2 getAnchorA() {
    return new Vec2(liquidfunJNI.Joint_getAnchorA(swigCPtr, this), true);
  }

  public Vec2 getAnchorB() {
    return new Vec2(liquidfunJNI.Joint_getAnchorB(swigCPtr, this), true);
  }

  public Vec2 getReactionForce(float inv_dt) {
    return new Vec2(liquidfunJNI.Joint_getReactionForce(swigCPtr, this, inv_dt), true);
  }

  public float getReactionTorque(float inv_dt) {
    return liquidfunJNI.Joint_getReactionTorque(swigCPtr, this, inv_dt);
  }

  public Joint getNext() {
    long cPtr = liquidfunJNI.Joint_getNext__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new Joint(cPtr, false);
  }

  public java.lang.Object getUserData() {
    return liquidfunJNI.Joint_getUserData(swigCPtr, this);
  }

  public void setUserData(java.lang.Object data) {
    liquidfunJNI.Joint_setUserData(swigCPtr, this, data);
  }

  public boolean isActive() {
    return liquidfunJNI.Joint_isActive(swigCPtr, this);
  }

  public boolean getCollideConnected() {
    return liquidfunJNI.Joint_getCollideConnected(swigCPtr, this);
  }

  public void dump() {
    liquidfunJNI.Joint_dump(swigCPtr, this);
  }

  public void shiftOrigin(Vec2 newOrigin) {
    liquidfunJNI.Joint_shiftOrigin(swigCPtr, this, Vec2.getCPtr(newOrigin), newOrigin);
  }

}
