/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public final class JointType {
  public final static int e_unknownJoint = 0;
  public final static int e_revoluteJoint = e_unknownJoint + 1;
  public final static int e_prismaticJoint = e_revoluteJoint + 1;
  public final static int e_distanceJoint = e_prismaticJoint + 1;
  public final static int e_pulleyJoint = e_distanceJoint + 1;
  public final static int e_mouseJoint = e_pulleyJoint + 1;
  public final static int e_gearJoint = e_mouseJoint + 1;
  public final static int e_wheelJoint = e_gearJoint + 1;
  public final static int e_weldJoint = e_wheelJoint + 1;
  public final static int e_frictionJoint = e_weldJoint + 1;
  public final static int e_ropeJoint = e_frictionJoint + 1;
  public final static int e_motorJoint = e_ropeJoint + 1;
}

