/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public final class LimitState {
  public final static int e_inactiveLimit = 0;
  public final static int e_atLowerLimit = e_inactiveLimit + 1;
  public final static int e_atUpperLimit = e_atLowerLimit + 1;
  public final static int e_equalLimits = e_atUpperLimit + 1;
}

