/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class ManifoldPoint {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ManifoldPoint(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ManifoldPoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ManifoldPoint obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_ManifoldPoint(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLocalPoint(Vec2 value) {
    liquidfunJNI.ManifoldPoint_localPoint_set(swigCPtr, this, Vec2.getCPtr(value), value);
  }

  public Vec2 getLocalPoint() {
    return new Vec2(liquidfunJNI.ManifoldPoint_localPoint_get(swigCPtr, this), false);
  }

  public void setNormalImpulse(float value) {
    liquidfunJNI.ManifoldPoint_normalImpulse_set(swigCPtr, this, value);
  }

  public float getNormalImpulse() {
    return liquidfunJNI.ManifoldPoint_normalImpulse_get(swigCPtr, this);
  }

  public void setTangentImpulse(float value) {
    liquidfunJNI.ManifoldPoint_tangentImpulse_set(swigCPtr, this, value);
  }

  public float getTangentImpulse() {
    return liquidfunJNI.ManifoldPoint_tangentImpulse_get(swigCPtr, this);
  }

  public void setId(ContactID value) {
    liquidfunJNI.ManifoldPoint_id_set(swigCPtr, this, ContactID.getCPtr(value), value);
  }

  public ContactID getId() {
    return new ContactID(liquidfunJNI.ManifoldPoint_id_get(swigCPtr, this), false);
  }

  public ManifoldPoint() {
    this(liquidfunJNI.new_ManifoldPoint(), true);
  }

}
