/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class MotorJoint extends Joint {
  private transient long swigCPtr;

  protected MotorJoint(long cPtr, boolean cMemoryOwn) {
    super(liquidfunJNI.MotorJoint_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MotorJoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MotorJoint obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_MotorJoint(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Vec2 getAnchorA() {
    return new Vec2(liquidfunJNI.MotorJoint_getAnchorA(swigCPtr, this), true);
  }

  public Vec2 getAnchorB() {
    return new Vec2(liquidfunJNI.MotorJoint_getAnchorB(swigCPtr, this), true);
  }

  public Vec2 getReactionForce(float inv_dt) {
    return new Vec2(liquidfunJNI.MotorJoint_getReactionForce(swigCPtr, this, inv_dt), true);
  }

  public float getReactionTorque(float inv_dt) {
    return liquidfunJNI.MotorJoint_getReactionTorque(swigCPtr, this, inv_dt);
  }

  public void setLinearOffset(Vec2 linearOffset) {
    liquidfunJNI.MotorJoint_setLinearOffset(swigCPtr, this, Vec2.getCPtr(linearOffset), linearOffset);
  }

  public Vec2 getLinearOffset() {
    return new Vec2(liquidfunJNI.MotorJoint_getLinearOffset(swigCPtr, this), false);
  }

  public void setAngularOffset(float angularOffset) {
    liquidfunJNI.MotorJoint_setAngularOffset(swigCPtr, this, angularOffset);
  }

  public float getAngularOffset() {
    return liquidfunJNI.MotorJoint_getAngularOffset(swigCPtr, this);
  }

  public void setMaxForce(float force) {
    liquidfunJNI.MotorJoint_setMaxForce(swigCPtr, this, force);
  }

  public float getMaxForce() {
    return liquidfunJNI.MotorJoint_getMaxForce(swigCPtr, this);
  }

  public void setMaxTorque(float torque) {
    liquidfunJNI.MotorJoint_setMaxTorque(swigCPtr, this, torque);
  }

  public float getMaxTorque() {
    return liquidfunJNI.MotorJoint_getMaxTorque(swigCPtr, this);
  }

  public void setCorrectionFactor(float factor) {
    liquidfunJNI.MotorJoint_setCorrectionFactor(swigCPtr, this, factor);
  }

  public float getCorrectionFactor() {
    return liquidfunJNI.MotorJoint_getCorrectionFactor(swigCPtr, this);
  }

  public void dump() {
    liquidfunJNI.MotorJoint_dump(swigCPtr, this);
  }

}
