/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class MotorJointDef extends JointDef {
  private transient long swigCPtr;

  protected MotorJointDef(long cPtr, boolean cMemoryOwn) {
    super(liquidfunJNI.MotorJointDef_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MotorJointDef obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MotorJointDef obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_MotorJointDef(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public MotorJointDef() {
    this(liquidfunJNI.new_MotorJointDef(), true);
  }

  public void initialize(Body bodyA, Body bodyB) {
    liquidfunJNI.MotorJointDef_initialize(swigCPtr, this, Body.getCPtr(bodyA), bodyA, Body.getCPtr(bodyB), bodyB);
  }

  public void setLinearOffset(Vec2 value) {
    liquidfunJNI.MotorJointDef_linearOffset_set(swigCPtr, this, Vec2.getCPtr(value), value);
  }

  public Vec2 getLinearOffset() {
    return new Vec2(liquidfunJNI.MotorJointDef_linearOffset_get(swigCPtr, this), false);
  }

  public void setAngularOffset(float value) {
    liquidfunJNI.MotorJointDef_angularOffset_set(swigCPtr, this, value);
  }

  public float getAngularOffset() {
    return liquidfunJNI.MotorJointDef_angularOffset_get(swigCPtr, this);
  }

  public void setMaxForce(float value) {
    liquidfunJNI.MotorJointDef_maxForce_set(swigCPtr, this, value);
  }

  public float getMaxForce() {
    return liquidfunJNI.MotorJointDef_maxForce_get(swigCPtr, this);
  }

  public void setMaxTorque(float value) {
    liquidfunJNI.MotorJointDef_maxTorque_set(swigCPtr, this, value);
  }

  public float getMaxTorque() {
    return liquidfunJNI.MotorJointDef_maxTorque_get(swigCPtr, this);
  }

  public void setCorrectionFactor(float value) {
    liquidfunJNI.MotorJointDef_correctionFactor_set(swigCPtr, this, value);
  }

  public float getCorrectionFactor() {
    return liquidfunJNI.MotorJointDef_correctionFactor_get(swigCPtr, this);
  }

}
