/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class MouseJointDef extends JointDef {
  private transient long swigCPtr;

  protected MouseJointDef(long cPtr, boolean cMemoryOwn) {
    super(liquidfunJNI.MouseJointDef_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MouseJointDef obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MouseJointDef obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_MouseJointDef(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public MouseJointDef() {
    this(liquidfunJNI.new_MouseJointDef(), true);
  }

  public void setTarget(Vec2 value) {
    liquidfunJNI.MouseJointDef_target_set(swigCPtr, this, Vec2.getCPtr(value), value);
  }

  public Vec2 getTarget() {
    return new Vec2(liquidfunJNI.MouseJointDef_target_get(swigCPtr, this), false);
  }

  public void setMaxForce(float value) {
    liquidfunJNI.MouseJointDef_maxForce_set(swigCPtr, this, value);
  }

  public float getMaxForce() {
    return liquidfunJNI.MouseJointDef_maxForce_get(swigCPtr, this);
  }

  public void setFrequencyHz(float value) {
    liquidfunJNI.MouseJointDef_frequencyHz_set(swigCPtr, this, value);
  }

  public float getFrequencyHz() {
    return liquidfunJNI.MouseJointDef_frequencyHz_get(swigCPtr, this);
  }

  public void setDampingRatio(float value) {
    liquidfunJNI.MouseJointDef_dampingRatio_set(swigCPtr, this, value);
  }

  public float getDampingRatio() {
    return liquidfunJNI.MouseJointDef_dampingRatio_get(swigCPtr, this);
  }

}
