/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class ParticleContact {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ParticleContact(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParticleContact obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ParticleContact obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_ParticleContact(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIndices(int a, int b) {
    liquidfunJNI.ParticleContact_setIndices(swigCPtr, this, a, b);
  }

  public void setWeight(float w) {
    liquidfunJNI.ParticleContact_setWeight(swigCPtr, this, w);
  }

  public void setNormal(Vec2 n) {
    liquidfunJNI.ParticleContact_setNormal(swigCPtr, this, Vec2.getCPtr(n), n);
  }

  public void setFlags(long f) {
    liquidfunJNI.ParticleContact_setFlags(swigCPtr, this, f);
  }

  public int getIndexA() {
    return liquidfunJNI.ParticleContact_getIndexA(swigCPtr, this);
  }

  public int getIndexB() {
    return liquidfunJNI.ParticleContact_getIndexB(swigCPtr, this);
  }

  public float getWeight() {
    return liquidfunJNI.ParticleContact_getWeight(swigCPtr, this);
  }

  public Vec2 getNormal() {
    return new Vec2(liquidfunJNI.ParticleContact_getNormal(swigCPtr, this), false);
  }

  public long getFlags() {
    return liquidfunJNI.ParticleContact_getFlags(swigCPtr, this);
  }

  public boolean equals(ParticleContact rhs) {
    return liquidfunJNI.ParticleContact_equals(swigCPtr, this, ParticleContact.getCPtr(rhs), rhs);
  }

  public boolean approximatelyEqual(ParticleContact rhs) {
    return liquidfunJNI.ParticleContact_approximatelyEqual(swigCPtr, this, ParticleContact.getCPtr(rhs), rhs);
  }

  public ParticleContact() {
    this(liquidfunJNI.new_ParticleContact(), true);
  }

}
