/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public final class ParticleFlag {
  public final static ParticleFlag waterParticle = new ParticleFlag("waterParticle", liquidfunJNI.waterParticle_get());
  public final static ParticleFlag zombieParticle = new ParticleFlag("zombieParticle", liquidfunJNI.zombieParticle_get());
  public final static ParticleFlag wallParticle = new ParticleFlag("wallParticle", liquidfunJNI.wallParticle_get());
  public final static ParticleFlag springParticle = new ParticleFlag("springParticle", liquidfunJNI.springParticle_get());
  public final static ParticleFlag elasticParticle = new ParticleFlag("elasticParticle", liquidfunJNI.elasticParticle_get());
  public final static ParticleFlag viscousParticle = new ParticleFlag("viscousParticle", liquidfunJNI.viscousParticle_get());
  public final static ParticleFlag powderParticle = new ParticleFlag("powderParticle", liquidfunJNI.powderParticle_get());
  public final static ParticleFlag tensileParticle = new ParticleFlag("tensileParticle", liquidfunJNI.tensileParticle_get());
  public final static ParticleFlag colorMixingParticle = new ParticleFlag("colorMixingParticle", liquidfunJNI.colorMixingParticle_get());
  public final static ParticleFlag destructionListenerParticle = new ParticleFlag("destructionListenerParticle", liquidfunJNI.destructionListenerParticle_get());
  public final static ParticleFlag barrierParticle = new ParticleFlag("barrierParticle", liquidfunJNI.barrierParticle_get());
  public final static ParticleFlag staticPressureParticle = new ParticleFlag("staticPressureParticle", liquidfunJNI.staticPressureParticle_get());
  public final static ParticleFlag reactiveParticle = new ParticleFlag("reactiveParticle", liquidfunJNI.reactiveParticle_get());
  public final static ParticleFlag repulsiveParticle = new ParticleFlag("repulsiveParticle", liquidfunJNI.repulsiveParticle_get());
  public final static ParticleFlag fixtureContactListenerParticle = new ParticleFlag("fixtureContactListenerParticle", liquidfunJNI.fixtureContactListenerParticle_get());
  public final static ParticleFlag particleContactListenerParticle = new ParticleFlag("particleContactListenerParticle", liquidfunJNI.particleContactListenerParticle_get());
  public final static ParticleFlag fixtureContactFilterParticle = new ParticleFlag("fixtureContactFilterParticle", liquidfunJNI.fixtureContactFilterParticle_get());
  public final static ParticleFlag particleContactFilterParticle = new ParticleFlag("particleContactFilterParticle", liquidfunJNI.particleContactFilterParticle_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ParticleFlag swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ParticleFlag.class + " with value " + swigValue);
  }

  private ParticleFlag(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ParticleFlag(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ParticleFlag(String swigName, ParticleFlag swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ParticleFlag[] swigValues = { waterParticle, zombieParticle, wallParticle, springParticle, elasticParticle, viscousParticle, powderParticle, tensileParticle, colorMixingParticle, destructionListenerParticle, barrierParticle, staticPressureParticle, reactiveParticle, repulsiveParticle, fixtureContactListenerParticle, particleContactListenerParticle, fixtureContactFilterParticle, particleContactFilterParticle };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

