/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public final class PointState {
  public final static PointState nullState = new PointState("nullState");
  public final static PointState addState = new PointState("addState");
  public final static PointState persistState = new PointState("persistState");
  public final static PointState removeState = new PointState("removeState");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static PointState swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + PointState.class + " with value " + swigValue);
  }

  private PointState(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private PointState(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private PointState(String swigName, PointState swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static PointState[] swigValues = { nullState, addState, persistState, removeState };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

