/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class Position {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Position(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Position obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Position obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_Position(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setC(Vec2 value) {
    liquidfunJNI.Position_c_set(swigCPtr, this, Vec2.getCPtr(value), value);
  }

  public Vec2 getC() {
    return new Vec2(liquidfunJNI.Position_c_get(swigCPtr, this), false);
  }

  public void setA(float value) {
    liquidfunJNI.Position_a_set(swigCPtr, this, value);
  }

  public float getA() {
    return liquidfunJNI.Position_a_get(swigCPtr, this);
  }

  public Position() {
    this(liquidfunJNI.new_Position(), true);
  }

}
