/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class PrismaticJointDef extends JointDef {
  private transient long swigCPtr;

  protected PrismaticJointDef(long cPtr, boolean cMemoryOwn) {
    super(liquidfunJNI.PrismaticJointDef_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PrismaticJointDef obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(PrismaticJointDef obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_PrismaticJointDef(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PrismaticJointDef() {
    this(liquidfunJNI.new_PrismaticJointDef(), true);
  }

  public void initialize(Body bodyA, Body bodyB, Vec2 anchor, Vec2 axis) {
    liquidfunJNI.PrismaticJointDef_initialize(swigCPtr, this, Body.getCPtr(bodyA), bodyA, Body.getCPtr(bodyB), bodyB, Vec2.getCPtr(anchor), anchor, Vec2.getCPtr(axis), axis);
  }

  public void setLocalAnchorA(Vec2 value) {
    liquidfunJNI.PrismaticJointDef_localAnchorA_set(swigCPtr, this, Vec2.getCPtr(value), value);
  }

  public Vec2 getLocalAnchorA() {
    return new Vec2(liquidfunJNI.PrismaticJointDef_localAnchorA_get(swigCPtr, this), false);
  }

  public void setLocalAnchorB(Vec2 value) {
    liquidfunJNI.PrismaticJointDef_localAnchorB_set(swigCPtr, this, Vec2.getCPtr(value), value);
  }

  public Vec2 getLocalAnchorB() {
    return new Vec2(liquidfunJNI.PrismaticJointDef_localAnchorB_get(swigCPtr, this), false);
  }

  public void setLocalAxisA(Vec2 value) {
    liquidfunJNI.PrismaticJointDef_localAxisA_set(swigCPtr, this, Vec2.getCPtr(value), value);
  }

  public Vec2 getLocalAxisA() {
    return new Vec2(liquidfunJNI.PrismaticJointDef_localAxisA_get(swigCPtr, this), false);
  }

  public void setReferenceAngle(float value) {
    liquidfunJNI.PrismaticJointDef_referenceAngle_set(swigCPtr, this, value);
  }

  public float getReferenceAngle() {
    return liquidfunJNI.PrismaticJointDef_referenceAngle_get(swigCPtr, this);
  }

  public void setEnableLimit(boolean value) {
    liquidfunJNI.PrismaticJointDef_enableLimit_set(swigCPtr, this, value);
  }

  public boolean getEnableLimit() {
    return liquidfunJNI.PrismaticJointDef_enableLimit_get(swigCPtr, this);
  }

  public void setLowerTranslation(float value) {
    liquidfunJNI.PrismaticJointDef_lowerTranslation_set(swigCPtr, this, value);
  }

  public float getLowerTranslation() {
    return liquidfunJNI.PrismaticJointDef_lowerTranslation_get(swigCPtr, this);
  }

  public void setUpperTranslation(float value) {
    liquidfunJNI.PrismaticJointDef_upperTranslation_set(swigCPtr, this, value);
  }

  public float getUpperTranslation() {
    return liquidfunJNI.PrismaticJointDef_upperTranslation_get(swigCPtr, this);
  }

  public void setEnableMotor(boolean value) {
    liquidfunJNI.PrismaticJointDef_enableMotor_set(swigCPtr, this, value);
  }

  public boolean getEnableMotor() {
    return liquidfunJNI.PrismaticJointDef_enableMotor_get(swigCPtr, this);
  }

  public void setMaxMotorForce(float value) {
    liquidfunJNI.PrismaticJointDef_maxMotorForce_set(swigCPtr, this, value);
  }

  public float getMaxMotorForce() {
    return liquidfunJNI.PrismaticJointDef_maxMotorForce_get(swigCPtr, this);
  }

  public void setMotorSpeed(float value) {
    liquidfunJNI.PrismaticJointDef_motorSpeed_set(swigCPtr, this, value);
  }

  public float getMotorSpeed() {
    return liquidfunJNI.PrismaticJointDef_motorSpeed_get(swigCPtr, this);
  }

}
