/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class PrismaticJoint extends Joint {
  private transient long swigCPtr;

  protected PrismaticJoint(long cPtr, boolean cMemoryOwn) {
    super(liquidfunJNI.PrismaticJoint_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PrismaticJoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(PrismaticJoint obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_PrismaticJoint(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Vec2 getAnchorA() {
    return new Vec2(liquidfunJNI.PrismaticJoint_getAnchorA(swigCPtr, this), true);
  }

  public Vec2 getAnchorB() {
    return new Vec2(liquidfunJNI.PrismaticJoint_getAnchorB(swigCPtr, this), true);
  }

  public Vec2 getReactionForce(float inv_dt) {
    return new Vec2(liquidfunJNI.PrismaticJoint_getReactionForce(swigCPtr, this, inv_dt), true);
  }

  public float getReactionTorque(float inv_dt) {
    return liquidfunJNI.PrismaticJoint_getReactionTorque(swigCPtr, this, inv_dt);
  }

  public Vec2 getLocalAnchorA() {
    return new Vec2(liquidfunJNI.PrismaticJoint_getLocalAnchorA(swigCPtr, this), false);
  }

  public Vec2 getLocalAnchorB() {
    return new Vec2(liquidfunJNI.PrismaticJoint_getLocalAnchorB(swigCPtr, this), false);
  }

  public Vec2 getLocalAxisA() {
    return new Vec2(liquidfunJNI.PrismaticJoint_getLocalAxisA(swigCPtr, this), false);
  }

  public float getReferenceAngle() {
    return liquidfunJNI.PrismaticJoint_getReferenceAngle(swigCPtr, this);
  }

  public float getJointTranslation() {
    return liquidfunJNI.PrismaticJoint_getJointTranslation(swigCPtr, this);
  }

  public float getJointSpeed() {
    return liquidfunJNI.PrismaticJoint_getJointSpeed(swigCPtr, this);
  }

  public boolean isLimitEnabled() {
    return liquidfunJNI.PrismaticJoint_isLimitEnabled(swigCPtr, this);
  }

  public void enableLimit(boolean flag) {
    liquidfunJNI.PrismaticJoint_enableLimit(swigCPtr, this, flag);
  }

  public float getLowerLimit() {
    return liquidfunJNI.PrismaticJoint_getLowerLimit(swigCPtr, this);
  }

  public float getUpperLimit() {
    return liquidfunJNI.PrismaticJoint_getUpperLimit(swigCPtr, this);
  }

  public void setLimits(float lower, float upper) {
    liquidfunJNI.PrismaticJoint_setLimits(swigCPtr, this, lower, upper);
  }

  public boolean isMotorEnabled() {
    return liquidfunJNI.PrismaticJoint_isMotorEnabled(swigCPtr, this);
  }

  public void enableMotor(boolean flag) {
    liquidfunJNI.PrismaticJoint_enableMotor(swigCPtr, this, flag);
  }

  public void setMotorSpeed(float speed) {
    liquidfunJNI.PrismaticJoint_setMotorSpeed(swigCPtr, this, speed);
  }

  public float getMotorSpeed() {
    return liquidfunJNI.PrismaticJoint_getMotorSpeed(swigCPtr, this);
  }

  public void setMaxMotorForce(float force) {
    liquidfunJNI.PrismaticJoint_setMaxMotorForce(swigCPtr, this, force);
  }

  public float getMaxMotorForce() {
    return liquidfunJNI.PrismaticJoint_getMaxMotorForce(swigCPtr, this);
  }

  public float getMotorForce(float inv_dt) {
    return liquidfunJNI.PrismaticJoint_getMotorForce(swigCPtr, this, inv_dt);
  }

  public void dump() {
    liquidfunJNI.PrismaticJoint_dump(swigCPtr, this);
  }

}
