/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class RayCastInput {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RayCastInput(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RayCastInput obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RayCastInput obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_RayCastInput(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setP1(Vec2 value) {
    liquidfunJNI.RayCastInput_p1_set(swigCPtr, this, Vec2.getCPtr(value), value);
  }

  public Vec2 getP1() {
    return new Vec2(liquidfunJNI.RayCastInput_p1_get(swigCPtr, this), false);
  }

  public void setP2(Vec2 value) {
    liquidfunJNI.RayCastInput_p2_set(swigCPtr, this, Vec2.getCPtr(value), value);
  }

  public Vec2 getP2() {
    return new Vec2(liquidfunJNI.RayCastInput_p2_get(swigCPtr, this), false);
  }

  public void setMaxFraction(float value) {
    liquidfunJNI.RayCastInput_maxFraction_set(swigCPtr, this, value);
  }

  public float getMaxFraction() {
    return liquidfunJNI.RayCastInput_maxFraction_get(swigCPtr, this);
  }

  public RayCastInput() {
    this(liquidfunJNI.new_RayCastInput(), true);
  }

}
