/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class RayCastOutput {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RayCastOutput(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RayCastOutput obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RayCastOutput obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_RayCastOutput(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNormal(Vec2 value) {
    liquidfunJNI.RayCastOutput_normal_set(swigCPtr, this, Vec2.getCPtr(value), value);
  }

  public Vec2 getNormal() {
    return new Vec2(liquidfunJNI.RayCastOutput_normal_get(swigCPtr, this), false);
  }

  public void setFraction(float value) {
    liquidfunJNI.RayCastOutput_fraction_set(swigCPtr, this, value);
  }

  public float getFraction() {
    return liquidfunJNI.RayCastOutput_fraction_get(swigCPtr, this);
  }

  public RayCastOutput() {
    this(liquidfunJNI.new_RayCastOutput(), true);
  }

}
