/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class RevoluteJointDef extends JointDef {
  private transient long swigCPtr;

  protected RevoluteJointDef(long cPtr, boolean cMemoryOwn) {
    super(liquidfunJNI.RevoluteJointDef_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RevoluteJointDef obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RevoluteJointDef obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_RevoluteJointDef(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RevoluteJointDef() {
    this(liquidfunJNI.new_RevoluteJointDef(), true);
  }

  public void initialize(Body bodyA, Body bodyB, Vec2 anchor) {
    liquidfunJNI.RevoluteJointDef_initialize(swigCPtr, this, Body.getCPtr(bodyA), bodyA, Body.getCPtr(bodyB), bodyB, Vec2.getCPtr(anchor), anchor);
  }

  public void setLocalAnchorA(Vec2 value) {
    liquidfunJNI.RevoluteJointDef_localAnchorA_set(swigCPtr, this, Vec2.getCPtr(value), value);
  }

  public Vec2 getLocalAnchorA() {
    return new Vec2(liquidfunJNI.RevoluteJointDef_localAnchorA_get(swigCPtr, this), false);
  }

  public void setLocalAnchorB(Vec2 value) {
    liquidfunJNI.RevoluteJointDef_localAnchorB_set(swigCPtr, this, Vec2.getCPtr(value), value);
  }

  public Vec2 getLocalAnchorB() {
    return new Vec2(liquidfunJNI.RevoluteJointDef_localAnchorB_get(swigCPtr, this), false);
  }

  public void setReferenceAngle(float value) {
    liquidfunJNI.RevoluteJointDef_referenceAngle_set(swigCPtr, this, value);
  }

  public float getReferenceAngle() {
    return liquidfunJNI.RevoluteJointDef_referenceAngle_get(swigCPtr, this);
  }

  public void setEnableLimit(boolean value) {
    liquidfunJNI.RevoluteJointDef_enableLimit_set(swigCPtr, this, value);
  }

  public boolean getEnableLimit() {
    return liquidfunJNI.RevoluteJointDef_enableLimit_get(swigCPtr, this);
  }

  public void setLowerAngle(float value) {
    liquidfunJNI.RevoluteJointDef_lowerAngle_set(swigCPtr, this, value);
  }

  public float getLowerAngle() {
    return liquidfunJNI.RevoluteJointDef_lowerAngle_get(swigCPtr, this);
  }

  public void setUpperAngle(float value) {
    liquidfunJNI.RevoluteJointDef_upperAngle_set(swigCPtr, this, value);
  }

  public float getUpperAngle() {
    return liquidfunJNI.RevoluteJointDef_upperAngle_get(swigCPtr, this);
  }

  public void setEnableMotor(boolean value) {
    liquidfunJNI.RevoluteJointDef_enableMotor_set(swigCPtr, this, value);
  }

  public boolean getEnableMotor() {
    return liquidfunJNI.RevoluteJointDef_enableMotor_get(swigCPtr, this);
  }

  public void setMotorSpeed(float value) {
    liquidfunJNI.RevoluteJointDef_motorSpeed_set(swigCPtr, this, value);
  }

  public float getMotorSpeed() {
    return liquidfunJNI.RevoluteJointDef_motorSpeed_get(swigCPtr, this);
  }

  public void setMaxMotorTorque(float value) {
    liquidfunJNI.RevoluteJointDef_maxMotorTorque_set(swigCPtr, this, value);
  }

  public float getMaxMotorTorque() {
    return liquidfunJNI.RevoluteJointDef_maxMotorTorque_get(swigCPtr, this);
  }

}
