/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class RopeJointDef extends JointDef {
  private transient long swigCPtr;

  protected RopeJointDef(long cPtr, boolean cMemoryOwn) {
    super(liquidfunJNI.RopeJointDef_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RopeJointDef obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RopeJointDef obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_RopeJointDef(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RopeJointDef() {
    this(liquidfunJNI.new_RopeJointDef(), true);
  }

  public void setLocalAnchorA(Vec2 value) {
    liquidfunJNI.RopeJointDef_localAnchorA_set(swigCPtr, this, Vec2.getCPtr(value), value);
  }

  public Vec2 getLocalAnchorA() {
    return new Vec2(liquidfunJNI.RopeJointDef_localAnchorA_get(swigCPtr, this), false);
  }

  public void setLocalAnchorB(Vec2 value) {
    liquidfunJNI.RopeJointDef_localAnchorB_set(swigCPtr, this, Vec2.getCPtr(value), value);
  }

  public Vec2 getLocalAnchorB() {
    return new Vec2(liquidfunJNI.RopeJointDef_localAnchorB_get(swigCPtr, this), false);
  }

  public void setMaxLength(float value) {
    liquidfunJNI.RopeJointDef_maxLength_set(swigCPtr, this, value);
  }

  public float getMaxLength() {
    return liquidfunJNI.RopeJointDef_maxLength_get(swigCPtr, this);
  }

}
