/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class SimplexCache {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SimplexCache(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SimplexCache obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SimplexCache obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_SimplexCache(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMetric(float value) {
    liquidfunJNI.SimplexCache_metric_set(swigCPtr, this, value);
  }

  public float getMetric() {
    return liquidfunJNI.SimplexCache_metric_get(swigCPtr, this);
  }

  public void setCount(int value) {
    liquidfunJNI.SimplexCache_count_set(swigCPtr, this, value);
  }

  public int getCount() {
    return liquidfunJNI.SimplexCache_count_get(swigCPtr, this);
  }

  public void setIndexA(SWIGTYPE_p_unsigned_char value) {
    liquidfunJNI.SimplexCache_indexA_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getIndexA() {
    long cPtr = liquidfunJNI.SimplexCache_indexA_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setIndexB(SWIGTYPE_p_unsigned_char value) {
    liquidfunJNI.SimplexCache_indexB_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getIndexB() {
    long cPtr = liquidfunJNI.SimplexCache_indexB_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public SimplexCache() {
    this(liquidfunJNI.new_SimplexCache(), true);
  }

}
