/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class Stat {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Stat(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Stat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Stat obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_Stat(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Stat() {
    this(liquidfunJNI.new_Stat(), true);
  }

  public void record(float t) {
    liquidfunJNI.Stat_record(swigCPtr, this, t);
  }

  public int getCount() {
    return liquidfunJNI.Stat_getCount(swigCPtr, this);
  }

  public float getMean() {
    return liquidfunJNI.Stat_getMean(swigCPtr, this);
  }

  public float getMin() {
    return liquidfunJNI.Stat_getMin(swigCPtr, this);
  }

  public float getMax() {
    return liquidfunJNI.Stat_getMax(swigCPtr, this);
  }

  public void clear() {
    liquidfunJNI.Stat_clear(swigCPtr, this);
  }

}
