/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class Sweep {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Sweep(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Sweep obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Sweep obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_Sweep(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void getTransform(Transform xfb, float beta) {
    liquidfunJNI.Sweep_getTransform(swigCPtr, this, Transform.getCPtr(xfb), xfb, beta);
  }

  public void advance(float alpha) {
    liquidfunJNI.Sweep_advance(swigCPtr, this, alpha);
  }

  public void normalize() {
    liquidfunJNI.Sweep_normalize(swigCPtr, this);
  }

  public void setLocalCenter(Vec2 value) {
    liquidfunJNI.Sweep_localCenter_set(swigCPtr, this, Vec2.getCPtr(value), value);
  }

  public Vec2 getLocalCenter() {
    return new Vec2(liquidfunJNI.Sweep_localCenter_get(swigCPtr, this), false);
  }

  public void setC0(Vec2 value) {
    liquidfunJNI.Sweep_c0_set(swigCPtr, this, Vec2.getCPtr(value), value);
  }

  public Vec2 getC0() {
    return new Vec2(liquidfunJNI.Sweep_c0_get(swigCPtr, this), false);
  }

  public void setC(Vec2 value) {
    liquidfunJNI.Sweep_c_set(swigCPtr, this, Vec2.getCPtr(value), value);
  }

  public Vec2 getC() {
    return new Vec2(liquidfunJNI.Sweep_c_get(swigCPtr, this), false);
  }

  public void setA0(float value) {
    liquidfunJNI.Sweep_a0_set(swigCPtr, this, value);
  }

  public float getA0() {
    return liquidfunJNI.Sweep_a0_get(swigCPtr, this);
  }

  public void setA(float value) {
    liquidfunJNI.Sweep_a_set(swigCPtr, this, value);
  }

  public float getA() {
    return liquidfunJNI.Sweep_a_get(swigCPtr, this);
  }

  public void setAlpha0(float value) {
    liquidfunJNI.Sweep_alpha0_set(swigCPtr, this, value);
  }

  public float getAlpha0() {
    return liquidfunJNI.Sweep_alpha0_get(swigCPtr, this);
  }

  public Sweep() {
    this(liquidfunJNI.new_Sweep(), true);
  }

}
