/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class SWIGTYPE_p_b2Manifold {
  private transient long swigCPtr;

  protected SWIGTYPE_p_b2Manifold(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_b2Manifold() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_b2Manifold obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SWIGTYPE_p_b2Manifold obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

