/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class TimeStep {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TimeStep(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TimeStep obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(TimeStep obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_TimeStep(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDt(float value) {
    liquidfunJNI.TimeStep_dt_set(swigCPtr, this, value);
  }

  public float getDt() {
    return liquidfunJNI.TimeStep_dt_get(swigCPtr, this);
  }

  public void setInv_dt(float value) {
    liquidfunJNI.TimeStep_inv_dt_set(swigCPtr, this, value);
  }

  public float getInv_dt() {
    return liquidfunJNI.TimeStep_inv_dt_get(swigCPtr, this);
  }

  public void setDtRatio(float value) {
    liquidfunJNI.TimeStep_dtRatio_set(swigCPtr, this, value);
  }

  public float getDtRatio() {
    return liquidfunJNI.TimeStep_dtRatio_get(swigCPtr, this);
  }

  public void setVelocityIterations(int value) {
    liquidfunJNI.TimeStep_velocityIterations_set(swigCPtr, this, value);
  }

  public int getVelocityIterations() {
    return liquidfunJNI.TimeStep_velocityIterations_get(swigCPtr, this);
  }

  public void setPositionIterations(int value) {
    liquidfunJNI.TimeStep_positionIterations_set(swigCPtr, this, value);
  }

  public int getPositionIterations() {
    return liquidfunJNI.TimeStep_positionIterations_get(swigCPtr, this);
  }

  public void setParticleIterations(int value) {
    liquidfunJNI.TimeStep_particleIterations_set(swigCPtr, this, value);
  }

  public int getParticleIterations() {
    return liquidfunJNI.TimeStep_particleIterations_get(swigCPtr, this);
  }

  public void setWarmStarting(boolean value) {
    liquidfunJNI.TimeStep_warmStarting_set(swigCPtr, this, value);
  }

  public boolean getWarmStarting() {
    return liquidfunJNI.TimeStep_warmStarting_get(swigCPtr, this);
  }

  public TimeStep() {
    this(liquidfunJNI.new_TimeStep(), true);
  }

}
