/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class TreeNode {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TreeNode(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TreeNode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(TreeNode obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_TreeNode(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean isLeaf() {
    return liquidfunJNI.TreeNode_isLeaf(swigCPtr, this);
  }

  public void setAabb(AABB value) {
    liquidfunJNI.TreeNode_aabb_set(swigCPtr, this, AABB.getCPtr(value), value);
  }

  public AABB getAabb() {
    return new AABB(liquidfunJNI.TreeNode_aabb_get(swigCPtr, this), false);
  }

  public void setUserData(java.lang.Object value) {
    liquidfunJNI.TreeNode_userData_set(swigCPtr, this, value);
  }

  public java.lang.Object getUserData() {
    return liquidfunJNI.TreeNode_userData_get(swigCPtr, this);
  }

  public void setParent(int value) {
    liquidfunJNI.TreeNode_parent_set(swigCPtr, this, value);
  }

  public int getParent() {
    return liquidfunJNI.TreeNode_parent_get(swigCPtr, this);
  }

  public void setNext(int value) {
    liquidfunJNI.TreeNode_next_set(swigCPtr, this, value);
  }

  public int getNext() {
    return liquidfunJNI.TreeNode_next_get(swigCPtr, this);
  }

  public void setChild1(int value) {
    liquidfunJNI.TreeNode_child1_set(swigCPtr, this, value);
  }

  public int getChild1() {
    return liquidfunJNI.TreeNode_child1_get(swigCPtr, this);
  }

  public void setChild2(int value) {
    liquidfunJNI.TreeNode_child2_set(swigCPtr, this, value);
  }

  public int getChild2() {
    return liquidfunJNI.TreeNode_child2_get(swigCPtr, this);
  }

  public void setHeight(int value) {
    liquidfunJNI.TreeNode_height_set(swigCPtr, this, value);
  }

  public int getHeight() {
    return liquidfunJNI.TreeNode_height_get(swigCPtr, this);
  }

  public TreeNode() {
    this(liquidfunJNI.new_TreeNode(), true);
  }

}
