/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class Vec3 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Vec3(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Vec3 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Vec3 obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_Vec3(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Vec3() {
    this(liquidfunJNI.new_Vec3__SWIG_0(), true);
  }

  public Vec3(float x, float y, float z) {
    this(liquidfunJNI.new_Vec3__SWIG_1(x, y, z), true);
  }

  public void setZero() {
    liquidfunJNI.Vec3_setZero(swigCPtr, this);
  }

  public void set(float x_, float y_, float z_) {
    liquidfunJNI.Vec3_set(swigCPtr, this, x_, y_, z_);
  }

  public float length() {
    return liquidfunJNI.Vec3_length(swigCPtr, this);
  }

  public float normalize() {
    return liquidfunJNI.Vec3_normalize(swigCPtr, this);
  }

  public void setX(float value) {
    liquidfunJNI.Vec3_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return liquidfunJNI.Vec3_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    liquidfunJNI.Vec3_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return liquidfunJNI.Vec3_y_get(swigCPtr, this);
  }

  public void setZ(float value) {
    liquidfunJNI.Vec3_z_set(swigCPtr, this, value);
  }

  public float getZ() {
    return liquidfunJNI.Vec3_z_get(swigCPtr, this);
  }

}
