/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class Vec4 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Vec4(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Vec4 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Vec4 obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_Vec4(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Vec4() {
    this(liquidfunJNI.new_Vec4__SWIG_0(), true);
  }

  public Vec4(float x, float y, float z, float w) {
    this(liquidfunJNI.new_Vec4__SWIG_1(x, y, z, w), true);
  }

  public void setX(float value) {
    liquidfunJNI.Vec4_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return liquidfunJNI.Vec4_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    liquidfunJNI.Vec4_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return liquidfunJNI.Vec4_y_get(swigCPtr, this);
  }

  public void setZ(float value) {
    liquidfunJNI.Vec4_z_set(swigCPtr, this, value);
  }

  public float getZ() {
    return liquidfunJNI.Vec4_z_get(swigCPtr, this);
  }

  public void setW(float value) {
    liquidfunJNI.Vec4_w_set(swigCPtr, this, value);
  }

  public float getW() {
    return liquidfunJNI.Vec4_w_get(swigCPtr, this);
  }

}
