/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class Velocity {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Velocity(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Velocity obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Velocity obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_Velocity(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setV(Vec2 value) {
    liquidfunJNI.Velocity_v_set(swigCPtr, this, Vec2.getCPtr(value), value);
  }

  public Vec2 getV() {
    return new Vec2(liquidfunJNI.Velocity_v_get(swigCPtr, this), false);
  }

  public void setW(float value) {
    liquidfunJNI.Velocity_w_set(swigCPtr, this, value);
  }

  public float getW() {
    return liquidfunJNI.Velocity_w_get(swigCPtr, this);
  }

  public Velocity() {
    this(liquidfunJNI.new_Velocity(), true);
  }

}
