/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class Version {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Version(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Version obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Version obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_Version(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMajor(int value) {
    liquidfunJNI.Version_major_set(swigCPtr, this, value);
  }

  public int getMajor() {
    return liquidfunJNI.Version_major_get(swigCPtr, this);
  }

  public void setMinor(int value) {
    liquidfunJNI.Version_minor_set(swigCPtr, this, value);
  }

  public int getMinor() {
    return liquidfunJNI.Version_minor_get(swigCPtr, this);
  }

  public void setRevision(int value) {
    liquidfunJNI.Version_revision_set(swigCPtr, this, value);
  }

  public int getRevision() {
    return liquidfunJNI.Version_revision_get(swigCPtr, this);
  }

  public Version() {
    this(liquidfunJNI.new_Version(), true);
  }

}
