/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class WeldJoint extends Joint {
  private transient long swigCPtr;

  protected WeldJoint(long cPtr, boolean cMemoryOwn) {
    super(liquidfunJNI.WeldJoint_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WeldJoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(WeldJoint obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_WeldJoint(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Vec2 getAnchorA() {
    return new Vec2(liquidfunJNI.WeldJoint_getAnchorA(swigCPtr, this), true);
  }

  public Vec2 getAnchorB() {
    return new Vec2(liquidfunJNI.WeldJoint_getAnchorB(swigCPtr, this), true);
  }

  public Vec2 getReactionForce(float inv_dt) {
    return new Vec2(liquidfunJNI.WeldJoint_getReactionForce(swigCPtr, this, inv_dt), true);
  }

  public float getReactionTorque(float inv_dt) {
    return liquidfunJNI.WeldJoint_getReactionTorque(swigCPtr, this, inv_dt);
  }

  public Vec2 getLocalAnchorA() {
    return new Vec2(liquidfunJNI.WeldJoint_getLocalAnchorA(swigCPtr, this), false);
  }

  public Vec2 getLocalAnchorB() {
    return new Vec2(liquidfunJNI.WeldJoint_getLocalAnchorB(swigCPtr, this), false);
  }

  public float getReferenceAngle() {
    return liquidfunJNI.WeldJoint_getReferenceAngle(swigCPtr, this);
  }

  public void setFrequency(float hz) {
    liquidfunJNI.WeldJoint_setFrequency(swigCPtr, this, hz);
  }

  public float getFrequency() {
    return liquidfunJNI.WeldJoint_getFrequency(swigCPtr, this);
  }

  public void setDampingRatio(float ratio) {
    liquidfunJNI.WeldJoint_setDampingRatio(swigCPtr, this, ratio);
  }

  public float getDampingRatio() {
    return liquidfunJNI.WeldJoint_getDampingRatio(swigCPtr, this);
  }

  public void dump() {
    liquidfunJNI.WeldJoint_dump(swigCPtr, this);
  }

}
