/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class WorldManifold {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected WorldManifold(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WorldManifold obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(WorldManifold obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_WorldManifold(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void initialize(Manifold manifold, Transform xfA, float radiusA, Transform xfB, float radiusB) {
    liquidfunJNI.WorldManifold_initialize(swigCPtr, this, Manifold.getCPtr(manifold), manifold, Transform.getCPtr(xfA), xfA, radiusA, Transform.getCPtr(xfB), xfB, radiusB);
  }

  public void setNormal(Vec2 value) {
    liquidfunJNI.WorldManifold_normal_set(swigCPtr, this, Vec2.getCPtr(value), value);
  }

  public Vec2 getNormal() {
    return new Vec2(liquidfunJNI.WorldManifold_normal_get(swigCPtr, this), false);
  }

  public void setPoints(Vec2 value) {
    liquidfunJNI.WorldManifold_points_set(swigCPtr, this, Vec2.getCPtr(value), value);
  }

  public Vec2 getPoints() {
    long cPtr = liquidfunJNI.WorldManifold_points_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Vec2(cPtr, false);
  }

  public void setSeparations(SWIGTYPE_p_float value) {
    liquidfunJNI.WorldManifold_separations_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getSeparations() {
    long cPtr = liquidfunJNI.WorldManifold_separations_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public WorldManifold() {
    this(liquidfunJNI.new_WorldManifold(), true);
  }

}
